function [fitresult,gof] = createFit_P_base(vTime,avP_set)
%CREATEFIT(VTIME,AVP_SET)
%  Create a fit.
%
%  Data for 'Baseline_fitting_P_base' fit:
%      X Input : vTime
%      Y Output: avP_set
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Oct-2014 16:03:40


%% Fit: 'Baseline_fitting_P_agg'.
[xData, yData] = prepareCurveData(vTime,avP_set);

% Set up fittype and options.
ft = fittype('fourier6');
opts = fitoptions('Method','NonlinearLeastSquares');
opts.Display = 'Off';
opts.StartPoint = [0 0 0 0 0 0 0 0 0 0 0 0 0 3.63610260832152e-05];

% Fit model to data.
[fitresult, gof] = fit(xData,yData,ft,opts);

% Create a figure for the plots.
figure('Name','Baseline_fitting_P_base');

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult,xData,yData );
legend(h,'P_base vs. vTime','Baseline_fitting_P_base','Location','Best');
% Label axes
xlabel('vTime');
ylabel('P_base');
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot(fitresult,xData, yData,'residuals' );
legend(h,'Baseline_fitting_P_base - residuals','Zero Line','Location',...
    'Best');
% Label axes
xlabel('vTime');
ylabel('P_base');
grid on;

end


